### ISSUE TITLE
Mocha overrides

### ISSUE THREAD

**Issue by adelespinasse** [jspm/registry#1033]
The overrides file for Mocha includes
```
    "diff": "@empty",
```
which I think is probably why it behaves strangely when a test fails:
```
err  TypeError: diff.createPatch is not a function
    at unifiedDiff (file:///C:/Users/aldel/agora/playdoh/public/jspm_packages/npm/mocha@3.2.0/lib/reporters/base.js:417:18)
    at file:///C:/Users/aldel/agora/playdoh/public/jspm_packages/npm/mocha@3.2.0/lib/reporters/base.js:218:16
...
```

Mocha is trying to use `diff` to format its output for the failure (I assume), but `diff` is empty because of the override. Is this override needed for something?

**Comment by adelespinasse** [comment]
I got it to behave correctly by removing the override (directly editing the override in my package.json) and installing diff with `jspm install --dev npm:diff`. No idea why that override exists.

I don't have enough confidence about jspm configuration to submit a pull request.

**Comment by aluanhaddad** [comment]
See also related to #1022.

**Comment by adelespinasse** [comment]
Oh, I later noticed that this is a problem with the exceptions thrown by Chai, but not by Unexpected, and not if the test simply does something like `throw new Error('error')`. Possibly this is why @guybedford  didn't notice the issue when writing the Mocha overrides and/or [this article](http://guybedford.com/systemjs-mocha-istanbul). I guess Mocha has special handling for Chai's exceptions.

**Comment by aluanhaddad** [comment]
Honestly I know little about test frameworks such as mocha, chai, and sinon. Instead I use tape + `jspm run test/index` whenever I can because I like for to test frameworks to be simple and I dislike when they encourage mutating steps.

Thanks for linking that article here, it is indeed a great read and was a pleasure to read again.
