### ISSUE TITLE
mapbox-gl

### ISSUE THREAD

**Issue by guybedford** [jspm/registry#106]
Get it to work...

**Comment by guybedford** [comment]
Well I've got it to install with the fix in https://github.com/jspm/npm/commit/4f3b237f1d5be0a4a8c968ff7e21bc13e6c2b22e. Not sure how to test it...

**Comment by tiagocpontesp** [comment]
FYI Seems to be working through npm, on the beta, just had to also `jspm install npm:gl-matrix`.

**Comment by dtaalbers** [comment]
I am unable to install it via 

`jspm install npm:mapbox-gl`

I am running `jspm 0.16.15`

```
(node:7375) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:7375) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
     Looking up npm:mapbox-gl
     Updating registry cache...
     Downloading npm:mapbox-gl@0.19.1

warn Error on processPackageConfig
     Package.json dependency mapbox-gl-shaders set to github:mapbox/mapbox-gl-shaders#e4737bb136d718f9c5fe8d943380f05db6249b57, which is not a valid dependency format for npm.
     It's advisable to publish jspm-style packages to GitHub or another registry so conventions are clear.

err  Error: Error processing package config for npm:mapbox-gl.
         at /private-path/src/node_modules/jspm/node_modules/systemjs-builder/lib/builder.js:27:9
         at Object.lib$rsvp$events$$default.trigger (private-path/src/node_modules/rsvp/dist/rsvp.js:245:13)
         at Timeout._onTimeout (private-path/src/node_modules/rsvp/dist/rsvp.js:568:47)
         at tryOnTimeout (timers.js:224:11)
         at Timer.listOnTimeout (timers.js:198:5)

err  Error processing package config for npm:mapbox-gl.

warn Installation changes not saved.
```

Any suggestions @guybedford?

**Comment by vegafx12** [comment]
I was able to get it partially working using the github mapbox/mapbox-gl-js, but I ran into some issues with dependencies. I hope to resolve later this afternoon, but I'm very curious if anyone has gotten it working with the npm mapbox-gl package. @guybedford if you need me to be a guinea pig, I'm willing to help test if possible/needed

**Comment by guybedford** [comment]
Registry override PRs are welcome if you get something working. The commit reference for the shader is a problem though.

**Comment by salfield** [comment]
mapbox-gl depends on specific github commits (which I believe is still unsupported in jspm), and requires package.json. No doubt this could be solved with overrides. 

However, @lucaswoj has pointed out that there is no intention of supporting systemjs due to the fact that mapbox-gl is tightly integrated with browserify and webworkify. I haven't looked into it in detail but it seems that webworkify "requires" packages from a web worker, so without swapping out the webworkify dependency it won't be possible to get this running in systemjs.

https://github.com/mapbox/mapbox-gl-js/issues/2458

Maybe the recent [plugin-worker ](https://github.com/casperlamboo/plugin-worker) work by @casperlamboo could be helpful here, but it would also require digging in to the internals of mapbox-gl. Shame I like the look of mapbox-gl.

**Comment by DominicBoettger** [comment]
Did someboy try out to use the plugin-worker?
