### ISSUE TITLE
react-bootstrap

### ISSUE THREAD

**Issue by EliRibble** [jspm/registry#141]
jspm install npm:react-bootstrap -o "{peerDependencies: {'react': '0.12.2'}}"

**Comment by EliRibble** [comment]
Original was:
jspm install npm:react-bootstrap

warn GitHub credentials not provided so rate limits will apply.
     Use jspm endpoint config github to set this up.

     Looking up npm:react-bootstrap
     Updating registry cache...
     Downloading npm:react-bootstrap@0.13.3
     Looking up npm:react

err  No version match found for npm:react@>=0.12

warn Installation changes not saved.

**Comment by guybedford** [comment]
@EliRibble this is definitely working ok for me actually - are you using the latest jspm version?

**Comment by EliRibble** [comment]
Looks like I was on 0.10.3. Upgrading to 0.10.6 resolved it, thanks

**Comment by guybedford** [comment]
Great to hear that, will close these then.

**Comment by pedramphp** [comment]
@guybedford @EliRibble 
I'm on `jspm -v 0.16.29` but I can't get to install `react-bootstrap`
`jspm npm:react-bootstrap`

getting below error, can you verify if you can install `react-bootstrap` in the latest version ?
```
warn Error on lookup for github:jspm/nodelibs-assert
     Error: spawn EMFILE
         at errnoException (child_process.js:1011:11)
         at ChildProcess.spawn (child_process.js:958:11)
         at exports.spawn (child_process.js:746:9)
         at Object.exports.execFile (child_process.js:628:15)
         at exports.exec (child_process.js:591:18)
         at module.exports (/Users/mpedramrazi/Projects/node_modules/jspm/node_modules/jspm-github/exec-git.js:64:5)
         at /Users/mpedramrazi/Projects/node_modules/jspm/node_modules/jspm-github/github.js:378:7
         at lib$rsvp$$internal$$initializePromise (/Users/mpedramrazi/Projects/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1084:9)
         at new lib$rsvp$promise$$Promise (/Users/mpedramrazi/Projects/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:546:53)
         at GithubLocation.lookup (/Users/mpedramrazi/Projects/node_modules/jspm/node_modules/jspm-github/github.js:377:12)
         at then.then.active (/Users/mpedramrazi/Projects/node_modules/jspm/lib/registry.js:117:30)
         at lib$rsvp$$internal$$tryCatch (/Users/mpedramrazi/Projects/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1036:16)
         at lib$rsvp$$internal$$invokeCallback (/Users/mpedramrazi/Projects/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1048:17)
         at /Users/mpedramrazi/Projects/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:331:11
         at Object.lib$rsvp$asap$$flush [as _onImmediate] (/Users/mpedramrazi/Projects/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1198:9)
         at processImmediate [as _immediateCallback] (timers.js:354:15)

err  Error looking up github:jspm/nodelibs-assert.
```

**Comment by guybedford** [comment]
@pedramphp try increasing your OS ulimit. See eg http://stackoverflow.com/questions/19981065/nodejs-error-emfile-too-many-open-files-on-mac-os.
