### ISSUE TITLE
filterIgnoreAndFiles is broken

### ISSUE THREAD

**Issue by tauren** [jspm/registry#322]
Adding a `jspm.ignore` property in `package.json` causes `jspm install` to fail.

```
     Downloading npm:nid-chef-spices@0.0.8
err  TypeError: undefined is not a function
         at /Users/tmil11/stash/nid/chef/node_modules/jspm/lib/build.js:114:28
         at Array.forEach (native)
         at /Users/tmil11/stash/nid/chef/node_modules/jspm/lib/build.js:99:14
         at lib$rsvp$$internal$$tryCatch (/Users/tmil11/stash/nid/chef/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:489:16)
         at lib$rsvp$$internal$$invokeCallback (/Users/tmil11/stash/nid/chef/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:501:17)
         at lib$rsvp$$internal$$publish (/Users/tmil11/stash/nid/chef/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:472:11)
         at lib$rsvp$asap$$flush (/Users/tmil11/stash/nid/chef/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1290:9)
         at process._tickCallback (node.js:355:11)
```

I added a console.log to line 114 of build.js to see the content of the `ignore` variable:

```
ignore: { '0': 'decks',
  '1': 'docs',
  '2': 'config',
  '3': 'xls',
  '4': 'schemas' }
```

This object doesn't contain the function `some` that it appears it needs to in line 114. It looks like it is expected to be an array, but it is an object with numerical indexes as keys.

```
      if (ignore && ignore.some(function(ignoreFile) {
```

**Comment by tauren** [comment]
Sorry, created in wrong repo!
