### ISSUE TITLE
Issue with typeahead.js?

### ISSUE THREAD

**Issue by PWKad** [jspm/registry#448]
I'm running in to an issue with typeahead.js where it is trying to grab the typeahead.bundle file but is not appending `.js`, only `.`

When I go in to the `define` file and add `.js` it now properly appends but that becomes `.js.js` instead.  Am I doing something wrong?

Using with aurelia.

The specific error - 
```
Error: Error loading "templates/type-ahead" at http://localhost:9000/dist/templates/type-ahead.js
Unable to load dependency github:twitter/typeahead.js@0.11.1/dist/typeahead.bundle.
Unable to load dependency github:twitter/typeahead.js@0.11.1/dist/typeahead.bundle.
    at c (http://localhost:9000/jspm_packages/system.js:1:5640)
    at http://localhost:9000/jspm_packages/system.js:1:6055
    at $__global.upgradeSystemLoader.c.execute (http://localhost:9000/jspm_packages/system.js:1:14553)
    at f (http://localhost:9000/jspm_packages/system.js:1:5970)
    at l (http://localhost:9000/jspm_packages/system.js:1:4597)
    at Object.$__global.upgradeSystemLoader.e.instantiate.Promise.all.then.execute (http://localhost:9000/jspm_packages/system.js:1:8278)
    at o (http://localhost:9000/jspm_packages/es6-module-loader.js:7:18496)
    at p (http://localhost:9000/jspm_packages/es6-module-loader.js:7:18868)
    at j (http://localhost:9000/jspm_packages/es6-module-loader.js:7:16406)
    at k (http://localhost:9000/jspm_packages/es6-module-loader.js:7:16791)
```

**Comment by guybedford** [comment]
@PWKad this is working fine for me on the jspm beta - which version of jspm and SystemJS are you using?

**Comment by PWKad** [comment]
Not using the beta yet as it has breaking changes for me.  I was hoping this wasn't the issue as the registry feels out of sync with jspm if so.  Any way to reference the previous version of the registry to see if that is the case?

**Comment by guybedford** [comment]
@PWKad it looks like this just needs an override as it is detecting as a module format with a self-referenced require.

I'd suggest trying the standard jQuery-style override along the lines of:

`jspm install github:twitter/typeahead.js -o { shim: { 'dist/typeahead.bundle': { deps: ['jquery'] } }, dependencies: { jquery: '*' } }`

**Comment by PWKad** [comment]
Works perfect thanks again Guy!

(if anyone else stumbles on this add double quotes surrounding the override)

`
jspm install github:twitter/typeahead.js -o "{ shim: { 'dist/typeahead.bundle': { deps: ['jquery'] } }, dependencies: { jquery: '*' } }"
`

**Comment by guybedford** [comment]
Thanks for the update - I've added this in https://github.com/jspm/registry/commit/5dcd17d35ec6836ee91cfef328ecf04135192d5d to the registry so this should now work with no manual override necessary.
