### ISSUE TITLE
eslint fails under jspm install, succeeds under npm install

### ISSUE THREAD

**Issue by pauleveritt** [jspm/registry#463]
Here is the traceback when running after a jspm install:

/Users/paul/.nvm/versions/io.js/v2.3.4/bin/node /Users/paul/projects/tmp/ng2-helloworld/jspm_packages/npm/eslint@0.24.1/bin/eslint.js --format=checkstyle lib/main.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'concat-stream'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/paul/projects/tmp/ng2-helloworld/jspm_packages/npm/eslint@0.24.1/bin/eslint.js:3:16
    at Object.<anonymous> (/Users/paul/projects/tmp/ng2-helloworld/jspm_packages/npm/eslint@0.24.1/bin/eslint.js:36:3)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

Process finished with exit code 1

**Comment by guybedford** [comment]
Unfortunately jspm does not support execution in Node in this way. Typically it's best to stick to using jspm for the browser scenarios. In time the server scenarios will get better though. See https://github.com/jspm/jspm-cli/wiki/NodeJS-Usage for more info.

**Comment by pauleveritt** [comment]
Ah, makes sense, my apologies. Thanks, closing.
