### ISSUE TITLE
Residual effects of using jspm-git

### ISSUE THREAD

**Issue by adriatic** [jspm/registry#661]
Hello Guy

Someone talked me into changing the package.json references to Kendo from https://github.com/telerik/kendo-ui-core to 
```
    "jspm-bower-endpoint": "git+https://github.com/cengageLucas/jspm-bower-endpoint.git",
    "jspm-git": "^0.4.2",
```
so my app could access the kendo libraries from "bower endpoint" by using 'jspm-git'. 

I could not get the jspm-git to work no matter what I saw your advice to have it installed globally (I had it locally) - no changes. So, rather than fight some idiosyncrasies in the situation that I do not fully understand, I did everything I could in order to remove the use of jspm-git module. This includes removing all of the caches (`C:\Users\Nikolaj\AppData\Local\.jspm`) as well es content of `C:\Users\Nikolaj\AppData\Roaming\npm` and `C:\Users\Nikolaj\AppData\Roaming\npm-cache)` folders.

After all this (and hopefully fixing my package.json file (attached - note that I also attached the config.js for a good measure) trying to run `jspm install` I consistently get:
```
λ jspm install

err  Error: Cannot find module 'jspm-git'
         at Function.Module._resolveFilename (module.js:336:15)
         at Function.Module._load (module.js:286:25)
         at Module.require (module.js:365:17)
         at require (module.js:384:17)
         at Object.exports.load (C:\work\aurelia-ui-toolkits\aurelia-kendoui-plugin\node_modules\jspm\lib\registry.js:68:25)
         at new RegistryPath (C:\work\aurelia-ui-toolkits\aurelia-kendoui-plugin\node_modules\jspm\lib\config\loader.js:261:33)
         at Config.read (C:\work\aurelia-ui-toolkits\aurelia-kendoui-plugin\node_modules\jspm\lib\config\loader.js:126:26)
         at C:\work\aurelia-ui-toolkits\aurelia-kendoui-plugin\node_modules\jspm\lib\config.js:100:26
         at process._tickCallback (node.js:356:9)
         at Function.Module.runMain (module.js:477:11)

err  Unable to load registry kendo
```

**How do I find where is this request to `jspm-git` comes from. Is there a "verbose" flag to make jspm tell me that?**

Regards

Nik

[package.json](https://files.zenhub.io/564e10092d47521d4101de1b)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
[config.js](https://files.zenhub.io/564e10132d47521d4101de1e)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by adriatic** [comment]
#### Update

As I learned the hard way, **steps I took** to start from a clean slate, trying to remove the use of `jspm-git` - **are incomplete**. In addition to clearing all of the caches, and proper editing the `package.json` file to remove the references to `jspm-git` as well as **references to bower endpoints** that require the use of `jspm-git`, there is still a place where old "settings" remain persistent - `config.js`.

This in a sense should not be a surprise - as it is a perfect example of the dangers of keeping redundant information in the system. I believed that `config.js` file, produced by jspm by reading the `package.json` file will **always** represent the state of `package.json` file. 

Lesson learned: after changing the `package.json` file, delete the `config.js` file, have jspm regenerate the it, and then remember to manually add the aurelia specific babelOptions:
```
babelOptions: {
    "optional": [
      "es7.decorators",
      "es7.classProperties"
    ]
  },
```
I would care a lot to get your comments to this problem.

**Comment by guybedford** [comment]
The key point here is that the package.json represents the install intention, while the config.js file is the actual manifest of all installed files.
