### ISSUE TITLE
Using npm:text-encoder-lite

### ISSUE THREAD

**Issue by henrjk** [jspm/registry#713]
https://www.npmjs.com/package/text-encoder-lite 

I have a library project 'lib' which uses this module and I managed to set an override so that the two globals were available. Unfortunately I don't have the exact command I used anymore.

However in package.json of my lib project I have this:
```
  "jspm": {
    "registry": "github",
    "format": "es6",
    "directories": {
      "lib": "src"
    },
    "dependencies": {
...
      "text-encoder-lite": "npm:text-encoder-lite@^1.0.0",
    },
    "overrides": {
      "npm:text-encoder-lite@1.0.0": {
        "shim": {
          "index": {
            "exports": [
              "TextEncoderLite",
              "TextDecoderLite"
            ]
          }
        }
      }   
``` 

This has been installed with jspm 0.16.19 and my tests pass.

Now in an app consuming lib I started using jspm@beta. I am using the lib with the jspm link command so that it creates a symbolic link to its lib directory and also a json file.

When the app is started references to the TextEncoderLite and TextDecoderLite result in references errors in the lib.

As an attempt to fix this, I installed text-encoder-lite with the jspm beta (0.17.0-beta.2) using this command:
```
jspm install npm:text-encoder-lite -o "{format: 'global', shim: {index: { exports: ['TextEncoderLite', 'TextDecoderLite']}}}"
```

However this lead to a TypeError error in:
```
system.src.js:1461 Uncaught TypeError: p.split is not a functionreadMemberExpression @ system.src.js:1461(anonymous function) @ system.src.js:3533(anonymous function) @ system.src.js:3997complete @ system.src.js:2688
```
p is ['TextEncoderLite', 'TextDecoderLite'] in the debugger at this moment.

Some docs suggest that globals would be recognized automatically and so I tried this instead 
```
jspm install npm:text-encoder-lite -o "{format: 'global'}"
```
but then I see this error:
```
system.src.js:43 Uncaught (in promise) Error: TextEncoderLite is not defined
	Error loading http://localhost:9000/scripts/app.js
    at Xstr2utf8ab (http://localhost:9000/scripts/app.js:6:16)
    at System.register._export.execute (http://localhost:9000/scripts/app.js:19:31)
    at ensureEvaluated (http://localhost:9000/jspm/jspm_packages/system.src.js:3190:26)
    at Object.execute (http://localhost:9000/jspm/jspm_packages/system.src.js:3311:13)
    at doDynamicExecute (http://localhost:9000/jspm/jspm_packages/system.src.js:716:25)
    at link (http://localhost:9000/jspm/jspm_packages/system.src.js:912:20)
    at doLink (http://localhost:9000/jspm/jspm_packages/system.src.js:570:7)
    at updateLinkSetOnLoad (http://localhost:9000/jspm/jspm_packages/system.src.js:618:18)
    at http://localhost:9000/jspm/jspm_packages/system.src.js:430:11
```

The stack trace above is after I added some code directly in my app.js to avoid potential issues due to the linking. The code looks like this:
```JavaScript
import 'text-encoder-lite'
function Xstr2utf8ab (str) {
  return new TextEncoderLite('utf-8').encode(str)
}
function Xabutf82str (ab) {
  return new TextDecoderLite('utf-8').decode(ab)
}
console.log(Xabutf82str(Xstr2utf8ab('hello')))
```

Some questions: 
1. How to properly consume text-encoding-lite?
2. Should one even have to install indirect dependencies that a linked module requires if it needs overrides?
3. Are there issues with using different jspm version for the lib and the app?

**Comment by guybedford** [comment]
`exports` as an array is not supported in shims.

I'd suggest sticking with your original override that worked in jspm 0.16 and seeing if you can tell why it isn't working in jspm 0.17.

Are you definitely including the two jspm 0.17 config files correctly (with the browser configuration file included first)? Can you share the contents of `jspm_packages/npm/text-encoder-lite@1.0.0.json` when installed with the override in jspm 0.17?

**Comment by henrjk** [comment]
Here is some more information. 

I am issuing the same install command in 0.16 vs 0.17:

```
jspm install npm:text-encoder-lite \
    -o "{'shim': {'index': {'exports': ['TextEncoderLite', 'TextDecoderLite']}}}"
```

With jspm 0.16.25 it is working and I see this: 
```
--- file: jspm_packages/npm/text-encoder-lite@1.0.0.js
module.exports = require("npm:text-encoder-lite@1.0.0/index.js");

--- file: jspm_packages/npm/text-encoder-lite@1.0.0/index.js
/* */
"format global";
"exports TextEncoderLite,TextDecoderLite";
function TextEncoderLite() {
}
function TextDecoderLite() {
}

(function () {
'use strict';
... Rest of module
```

While with jspm 0.17 I see the mentioned error with these files:
```
--- file: jspm_packages/npm/text-encoder-lite@1.0.0.json:
{
  "main": "index.js",
  "meta": {
    "index.js": {
      "exports": [
        "TextEncoderLite",
        "TextDecoderLite"
      ]
    }
  },
  "format": "cjs"
}

--- file: jspm_packages/npm/text-encoder-lite@1.0.0/index.js:
function TextEncoderLite() {
}
function TextDecoderLite() {
}

(function () {
'use strict';
... Rest of modules.
```

So it appears that the text-encoder-lite@1.0.0.json file with 0.16 which simply does a require works while the more elaborate 0.17 config does not. The latter does use the not supported export array which explains why it fails. 
I will try to find out whether I see any other differences that might contribute.

**Comment by henrjk** [comment]
So I don't see any other obvious differences. And yes I did include the two jspm 0.17 config files correctly.

**Comment by guybedford** [comment]
@henrjk you are completely right, this is an undocumented breaking change. We can support this in jspm 0.17, but it would be dependent on https://github.com/systemjs/systemjs/issues/443.

**Comment by henrjk** [comment]
text-encoder-lite starts like this:

```JavaScript
function TextEncoderLite() {
}
function TextDecoderLite() {
}

(function () {
'use strict';
...
function utf8ToBytes (string, units) {
...
}());
```

This is used by ES6 code like this:
```JavaScript
/* global TextEncoderLite, TextDecoderLite */
import 'text-encoder-lite'

export function str2utf8ab (str) {
  return new TextEncoderLite('utf-8').encode(str)
}
export function abutf82str (ab) {
  return new TextDecoderLite('utf-8').decode(ab)
}
```

I have been debugging how system.js loads text-encoder-lite and also looked at system.js unit tests. 
With that I come to understand that the ES6 code above should work if jspm imports text-encoder-lite as global. 
Shimming or defining exports allows to determine which symbols the module exports. For example assume this could be achieved somehow one could write this ES6 code:

```JavaScript
import {TextEncoderLite, TextDecoderLite} from 'text-encoder-lite'
``` 

While this would (perhaps) be nicer, at the moment I'd be satisfied with simply importing the module as global so that TextEncoderLite and TextDecoderLite become properties of windows.
 
Now with jspm 0.16.19 I can install as follows
```console
$ jspm install npm:text-encoder-lite -o "{format: 'global'}"
``` 
And then use this with `import 'text-encoder-lite` as shown at the top of this comment. This works fine. 

However when I do the same with jspm 0.17.0-beta.5 then the import fails. jspm_packages/npm/text-encoder-lite@1.0.0.json looks like this:
```JSON
{
  "main": "index.js",
  "format": "global",
  "meta": {
    "*": {
      "globals": {
        "process": "process"
      }
    },
    "*.json": {
      "format": "json"
    },
    "index.js": {
      "globals": {
        "process": null
      }
    },
    "package.json": {
      "globals": {
        "process": null
      }
    }
  }
}
```

The error I am seeing is this:
```
Uncaught (in promise) Error: Cannot read property 'lastIndexOf' of null
	Error loading http://127.0.0.1:53774/jspm_packages/npm/text-encoder-lite@1.0.0/index.js as "text-encoder-lite" from http://127.0.0.1:53774/src/main.js
    at SystemJSLoader.booleanConditional (http://127.0.0.1:53774/jspm_packages/system.src.js:4458:28)
    at SystemJSLoader.normalize (http://127.0.0.1:53774/jspm_packages/system.src.js:4483:33)
    at SystemJSLoader.<anonymous> (http://127.0.0.1:53774/jspm_packages/system.src.js:3287:55)
    at SystemJSLoader.<anonymous> (http://127.0.0.1:53774/jspm_packages/system.src.js:3512:24)
    at SystemJSLoader.<anonymous> (http://127.0.0.1:53774/jspm_packages/system.src.js:3760:26)
    at SystemJSLoader.<anonymous> (http://127.0.0.1:53774/jspm_packages/system.src.js:4107:26)
    at SystemJSLoader.instantiate (http://127.0.0.1:53774/jspm_packages/system.src.js:4345:28)
    at http://127.0.0.1:53774/jspm_packages/system.src.js:346:33
```

**Comment by henrjk** [comment]
After some debugging I noticed that this was caused by having a different value for `globalEvaluationScope`.

In my 0.17 beta a freshly generated jspm.config.js has this:
```JavaScript
globalEvaluationScope: false,
```

Now in my 0.16 context this was set to true. The difference is that this will `eval` the source of text-encoding-lite while with globalEvaluationScope it is evaluated with `new Function( <source-of-text-encoding-lite>).call(__global)`. In the latter the function declaration are local to the constructed functions and this do not make it to the global scope.

I am not sure whether I played around with the original setting for 0.16 or whether this was as generated.

**Comment by henrjk** [comment]
The globalEvaluationScope: true alone did not make this work on jspm 0.17. 
I forgot to mention that I also hand edited the file jspm_packages/npm/text-encoder-lite@1.0.0.json mentioned two comments up to:
```
{
  "main": "index.js",
  "format": "global"
}
```

**Comment by guybedford** [comment]
@henrjk thanks for the analysis here. There's a few things going on there.

1. Support for `null` globals was not provided which was throwing, this is a bug fixed in https://github.com/systemjs/systemjs/commit/5164adbfffd278d9fe7e40131d76871f5b5336a3.
2. `globalEvaluationScope: false` stops SystemJS from being able to detect exports of that form. The approach in jspm 0.17 is to rather set `exports` metadata so the config file looks like:

```json
{
  "main": "index.js",
  "format": "global",
  "meta": {
    "*": {
      "globals": {
        "process": "process"
      }
    },
    "*.json": {
      "format": "json"
    },
    "index.js": {
      "globals": {
        "process": null
      },
      "exports": "TextEncoderLite"
    },
    "package.json": {
      "globals": {
        "process": null
      }
    }
  }
}
```

3. The final problem is that the above approach does not cover the case where you effectively want exports as an array - `"exports": ["TextEncoderLite", "TextDecoderLite"]`, this feature is tracking in https://github.com/systemjs/systemjs/issues/443 and I will prioritise that for jspm 0.17.

In the mean time your best work around is probably to ensure you have the fix for `process: null` as linked above (or just remove the `process: null` entries from the package.json, and then set `globalEvaluationScope: true`.
