### ISSUE TITLE
Error: Unable to inline conditional dependency

### ISSUE THREAD

**Issue by ggutenberg** [jspm/registry#730]
I've added a 3rd-party package (es6-template-strings) and it or its dependencies seem to be breaking my ability to create a sfx bundle.  I don't really understand what the error means, or what it's suggesting I do, so any help is appreciated.

You might be wondering why I'm installing an es6 template strings library when jspm provides that functionality with babel, but it's because I'm using it to parse dynamic strings, which don't get included in the bundling process.  

Here are the details:

jspm version
`0.16.25`

Bundle command
`jspm bundle-sfx index.js toolkit-js.js`

Bundle output
```
$ jspm bundle-sfx index.js toolkit-js.js
     Building the single-file sfx bundle for index.js...

err  Error: Unable to inline conditional dependency npm:es5-ext@0.10.11/string/#/contains. Try including the es5-ext/string/#/contains dependency of npm:d@0.1.1/index in the build.
         at /usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:656:17
         at Array.forEach (native)
         at /usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:647:32
         at Array.forEach (native)
         at /usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:634:23
         at tryCatcher (/usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/util.js:11:23)
         at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:491:31)
         at Promise._settlePromise (/usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:548:18)
         at Promise._settlePromise0 (/usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:593:10)
         at Promise._settlePromises (/usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:676:18)
         at Async._drainQueue (/usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:125:16)
         at Async._drainQueues (/usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:135:10)
         at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:16:14)
         at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Installed using 
`jspm install npm:es6-template-strings`

Added to code using
`import es6TemplateStrings from 'es6-template-strings';`

package.json
```
{
  "scripts": {
    "serveit": "browser-sync start --files 'src/**/*.html,src/**/*.css,src/**/*.js' --server 'src'"
  },
  "jspm": {
    "directories": {
      "baseURL": "src"
    },
    "dependencies": {
      "es6-template-strings": "npm:es6-template-strings@^2.0.0"
    },
    "devDependencies": {
      "babel": "npm:babel-core@5.8.35",
      "babel-runtime": "npm:babel-runtime@5.8.35",
      "core-js": "npm:core-js@1.2.6"
    }
  },
  "devDependencies": {
    "browser-sync": "2.9.11"
  },
  "dependencies": {
    "xmlhttprequest": "1.8.0"
  }
}
```

config.js
```
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },

  meta: {
    "core-js/library/modules/$.global.js": {
      "esmExports": false
    }
  },

  map: {
    "babel": "npm:babel-core@5.8.35",
    "babel-runtime": "npm:babel-runtime@5.8.35",
    "core-js": "npm:core-js@1.2.6",
    "es6-template-strings": "npm:es6-template-strings@2.0.0",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:babel-runtime@5.8.35": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:core-js@1.2.6": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:d@0.1.1": {
      "es5-ext": "npm:es5-ext@0.10.11"
    },
    "npm:es5-ext@0.10.11": {
      "es6-iterator": "npm:es6-iterator@2.0.0",
      "es6-symbol": "npm:es6-symbol@3.0.2",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:es6-iterator@2.0.0": {
      "d": "npm:d@0.1.1",
      "es5-ext": "npm:es5-ext@0.10.11",
      "es6-symbol": "npm:es6-symbol@3.0.2"
    },
    "npm:es6-symbol@3.0.2": {
      "d": "npm:d@0.1.1",
      "es5-ext": "npm:es5-ext@0.10.11"
    },
    "npm:es6-template-strings@2.0.0": {
      "es5-ext": "npm:es5-ext@0.10.11",
      "esniff": "npm:esniff@1.0.0"
    },
    "npm:esniff@1.0.0": {
      "d": "npm:d@0.1.1",
      "es5-ext": "npm:es5-ext@0.10.11"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
```

**Comment by guybedford** [comment]
Thanks, this is actually a bug. Fixed in https://github.com/systemjs/builder/commit/a91433b0afef30e34b9505a3179a5c1923ebc7a7.

**Comment by guybedford** [comment]
(The release will follow in the next few days)
