### ISSUE TITLE
Support getting node-forge working (.17beta14)

### ISSUE THREAD

**Issue by adamburgess** [jspm/registry#905]
node-forge is defined as an AMD module, even though it does work in node (through CJS).
The problem lies that node-forge tries to require `crypto` if it detects a node system, which would work usually - but since the AMD format is selected this fails:

```
err  Error: Module not already loaded loading "crypto" as /jspm_packages/github/jspm/nodelibs-crypto@0.2.0-alpha.
      at Array.initModule (/jspm_packages/npm/node-forge@0.6.39/js/pbkdf2.js:20:12)
      at Array.module.exports (/jspm_packages/npm/node-forge@0.6.39/js/pbkdf2.js:246:14)
      at Array.module.exports (/jspm_packages/npm/node-forge@0.6.39/js/pbe.js:943:14)
      at Array.module.exports (/jspm_packages/npm/node-forge@0.6.39/js/pki.js:130:14)
      at Array.module.exports (/jspm_packages/npm/node-forge@0.6.39/js/tls.js:4289:14)
      at Array.module.exports (/jspm_packages/npm/node-forge@0.6.39/js/aesCipherSuites.js:320:14)
      at Object.module.exports (/jspm_packages/npm/node-forge@0.6.39/js/forge.js:41:14)
      at defineFunc (/jspm_packages/npm/node-forge@0.6.39/js/forge.js:47:10)
      at /jspm_packages/npm/node-forge@0.6.39/js/forge.js:90:14
  Error loading /src/test.js
```

Changing the format to cjs gives me lots of problems, e.g. I have to manually set the dependencies for all files, and even then I still can't get it to work:

```
err  ReferenceError: forge is not defined
      at /jspm_packages/npm/node-forge@0.6.39/js/http.js:17:4
      at Object.<anonymous> (/jspm_packages/npm/node-forge@0.6.39/js/http.js:1369:3)
      at /jspm_packages/npm/node-forge@0.6.39/js/http.js:1371:4
      at /jspm_packages/npm/node-forge@0.6.39/js/http.js:1372:3
      at Object.exports.runInThisContext (vm.js:54:17)
  Evaluating /jspm_packages/npm/node-forge@0.6.39/js/http.js
  Error loading /src/test.js
```

There is a manual `disableNativeCode` boolean that I can turn to false to prevent forge from loading the crypto module, but I do want this to be loaded, and even so: I can't load the library in order to set that boolean to false, the error happens before I can run anything

any support would be great :)

**Comment by guybedford** [comment]
Try adding 'crypto' to the metadata deps?

**Comment by adamburgess** [comment]
```js
"npm:node-forge@0.6.39": {
  "meta": {
    "js/*.js": {
      "deps": [
        "crypto"
      ]
    }
  }
}
```
like this, in the overrides?
doesn't seem to work...

**Comment by guybedford** [comment]
What is happening is that node-forge is detecting NodeJS and then using CommonJS require in `js/pbkdf2.js`.

Unfortunately there is no way around that apart from just using CommonJS entirely for the project as that require detection on line 20 of pbkdf can't be altered through a different format change etc.

So I'd suggest trying `jspm install npm:node-forge -o format=cjs`. If you really want to exclude the extra Browserify deps, use `jspm install npm:node-forge -o meta[js/pbkdf2.js].format=cjs`, but that will likely then only hit the next issue after that needing to do `jspm install npm:node-forge -o "meta[js/pbkdf2.js]={format:'cjs',deps:['./hmac','./md','./util','crypto'],cjsDeferDepsExecute:false}"` and so on.
